@BookRest_HostAddress = http://localhost:5041

POST {{BookRest_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "owner@example.com",
  "password": "123456789Mm!"
}

> {% client.global.set("accessToken",  response.body.accessToken);  %}
<> {% client.global.set("refreshToken", response.body.refreshToken); %}

#####
POST {{BookRest_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "username":  "restowner2",
  "email": "owner@example2.com",
  "phonenumber": "0772110007",
  "password": "123456789Mm!"
}

#####
POST {{BookRest_HostAddress}}/api/restaurants
Content-Type: application/json

{
  
}